

[METADATA]
name = "Carib Coin"
symbol = "XCR"
description = "Decentralized XRPL-based coin tailored for the Caribbean and wider regional trading structure."
url = "https://github.com/maicoostar/XCR"
logo = "https://raw.githubusercontent.com/maicoostar/XCR/main/XCR_logo.png"
